//
// Autogenerated from indy-sdk main header files (indy_*.h)
//

#include <stdio.h>
#include "findy_glue.h"
#include "findy_callback_types.h"

// cgo generated
#include "_cgo_export.h"

#define CALLBACK_FUNCTION_HERE (indy_handler_str)strHandler


indy_error_t findy_issuer_create_schema(indy_handle_t command_handle, char *issuer_did, char *name, char *version, char *attr_names ) {
	indy_error_t err = indy_issuer_create_schema(command_handle, issuer_did, name, version, attr_names, (indy_handler_str_str)strStrHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_issuer_create_and_store_credential_def(indy_handle_t command_handle, indy_handle_t wallet_handle, char *issuer_did, char *schema_json, char *tag, char *signature_type, char *config_json ) {
	indy_error_t err = indy_issuer_create_and_store_credential_def(command_handle, wallet_handle, issuer_did, schema_json, tag, signature_type, config_json, (indy_handler_str_str)strStrHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_issuer_create_and_store_revoc_reg(indy_handle_t command_handle, indy_handle_t wallet_handle, char *issuer_did, char *revoc_def_type, char *tag, char *cred_def_id, char *config_json, indy_handle_t tails_writer_handle ) {
	indy_error_t err = indy_issuer_create_and_store_revoc_reg(command_handle, wallet_handle, issuer_did, revoc_def_type, tag, cred_def_id, config_json, tails_writer_handle, (indy_handler_str_str_str)strStrStrHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_issuer_create_credential_offer(indy_handle_t command_handle, indy_handle_t wallet_handle, char *cred_def_id ) {
	indy_error_t err = indy_issuer_create_credential_offer(command_handle, wallet_handle, cred_def_id, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_issuer_create_credential(indy_handle_t command_handle, indy_handle_t wallet_handle, char *cred_offer_json, char *cred_req_json, char *cred_values_json, char *rev_reg_id, indy_handle_t blob_storage_reader_handle ) {
	indy_error_t err = indy_issuer_create_credential(command_handle, wallet_handle, cred_offer_json, cred_req_json, cred_values_json, rev_reg_id, blob_storage_reader_handle, (indy_handler_str_str_str)strStrStrHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_issuer_revoke_credential(indy_handle_t command_handle, indy_handle_t wallet_handle, indy_handle_t blob_storage_reader_handle, char *rev_reg_id, char *cred_revoc_id ) {
	indy_error_t err = indy_issuer_revoke_credential(command_handle, wallet_handle, blob_storage_reader_handle, rev_reg_id, cred_revoc_id, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

/*extern indy_error_t indy_issuer_recover_credential(indy_handle_t command_handle, indy_handle_t wallet_handle, indy_handle_t blob_storage_reader_handle, char *rev_reg_id, char *cred_revoc_id);*/
indy_error_t findy_issuer_merge_revocation_registry_deltas(indy_handle_t command_handle, char *rev_reg_delta_json, char *other_rev_reg_delta_json ) {
	indy_error_t err = indy_issuer_merge_revocation_registry_deltas(command_handle, rev_reg_delta_json, other_rev_reg_delta_json, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_create_master_secret(indy_handle_t command_handle, indy_handle_t wallet_handle, char *master_secret_id ) {
	indy_error_t err = indy_prover_create_master_secret(command_handle, wallet_handle, master_secret_id, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_create_credential_req(indy_handle_t command_handle, indy_handle_t wallet_handle, char *prover_did, char *cred_offer_json, char *cred_def_json, char *master_secret_id ) {
	indy_error_t err = indy_prover_create_credential_req(command_handle, wallet_handle, prover_did, cred_offer_json, cred_def_json, master_secret_id,  (indy_handler_str_str)strStrHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_store_credential(indy_handle_t command_handle, indy_handle_t wallet_handle, char *cred_id, char *cred_req_metadata_json, char *cred_json, char *cred_def_json, char *rev_reg_def_json ) {
	indy_error_t err = indy_prover_store_credential(command_handle, wallet_handle, cred_id, cred_req_metadata_json, cred_json, cred_def_json, rev_reg_def_json, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_get_credentials(indy_handle_t command_handle, indy_handle_t wallet_handle, char *filter_json ) {
	indy_error_t err = indy_prover_get_credentials(command_handle, wallet_handle, filter_json, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_get_credential(indy_handle_t command_handle, indy_handle_t wallet_handle, char *cred_id ) {
	indy_error_t err = indy_prover_get_credential(command_handle, wallet_handle, cred_id, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_search_credentials(indy_handle_t command_handle, indy_handle_t wallet_handle, char *query_json ) {
	indy_error_t err = indy_prover_search_credentials(command_handle, wallet_handle, query_json, (indy_handler_handle_u32)handleU32Handler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_fetch_credentials(indy_handle_t command_handle, indy_handle_t search_handle, indy_u32_t count ) {
	indy_error_t err = indy_prover_fetch_credentials(command_handle, search_handle, count, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_close_credentials_search(indy_handle_t command_handle, indy_handle_t search_handle ) {
	indy_error_t err = indy_prover_close_credentials_search(command_handle, search_handle, (indy_handler)handler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_get_credentials_for_proof_req(indy_handle_t command_handle, indy_handle_t wallet_handle, char *proof_request_json ) {
	indy_error_t err = indy_prover_get_credentials_for_proof_req(command_handle, wallet_handle, proof_request_json, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_search_credentials_for_proof_req(indy_handle_t command_handle, indy_handle_t wallet_handle, char *proof_request_json, char *extra_query_json ) {
	indy_error_t err = indy_prover_search_credentials_for_proof_req(command_handle, wallet_handle, proof_request_json, extra_query_json, (indy_handler_handle)handleHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_fetch_credentials_for_proof_req(indy_handle_t command_handle, indy_handle_t search_handle, char*item_referent, indy_u32_t count ) {
	indy_error_t err = indy_prover_fetch_credentials_for_proof_req(command_handle, search_handle, item_referent, count, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_close_credentials_search_for_proof_req(indy_handle_t command_handle, indy_handle_t search_handle ) {
	indy_error_t err = indy_prover_close_credentials_search_for_proof_req(command_handle, search_handle, (indy_handler)handler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_prover_create_proof(indy_handle_t command_handle, indy_handle_t wallet_handle, char *proof_req_json, char *requested_credentials_json, char *master_secret_name, char *schemas_json, char *credential_defs_json, char *rev_states_json ) {
	indy_error_t err = indy_prover_create_proof(command_handle, wallet_handle, proof_req_json, requested_credentials_json, master_secret_name, schemas_json, credential_defs_json, rev_states_json, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_verifier_verify_proof(indy_handle_t command_handle, char *proof_request_json, char *proof_json, char *schemas_json, char *credential_defs_jsons, char *rev_reg_defs_json, char *rev_regs_json ) {
	indy_error_t err = indy_verifier_verify_proof(command_handle, proof_request_json, proof_json, schemas_json, credential_defs_jsons, rev_reg_defs_json, rev_regs_json, (indy_handler_bool)boolHandler );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_create_revocation_state(indy_handle_t command_handle, indy_handle_t blob_storage_reader_handle, char *rev_reg_def_json, char *rev_reg_delta_json, indy_u64_t timestamp, char *cred_rev_id ) {
	indy_error_t err = indy_create_revocation_state(command_handle, blob_storage_reader_handle, rev_reg_def_json, rev_reg_delta_json, timestamp, cred_rev_id, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_update_revocation_state(indy_handle_t command_handle, indy_handle_t blob_storage_reader_handle, char *rev_state_json, char *rev_reg_def_json, char *rev_reg_delta_json, indy_u64_t timestamp, char *cred_rev_id ) {
	indy_error_t err = indy_update_revocation_state(command_handle, blob_storage_reader_handle, rev_state_json, rev_reg_def_json, rev_reg_delta_json, timestamp, cred_rev_id, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

