//
// Autogenerated from indy-sdk main header files (indy_*.h)
//

#include <stdio.h>
#include "findy_glue.h"
#include "findy_callback_types.h"

// cgo generated
#include "_cgo_export.h"

indy_error_t findy_create_wallet(indy_handle_t command_handle, char*config, char*credentials ) {
	indy_error_t err = indy_create_wallet(command_handle, config, credentials, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_open_wallet(indy_handle_t command_handle, char*config, char*credentials ) {
	indy_error_t err = indy_open_wallet(command_handle, config, credentials, (indy_handler_handle)handleHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_export_wallet(indy_handle_t command_handle, indy_handle_t wallet_handle, char*export_config_json ) {
	indy_error_t err = indy_export_wallet(command_handle, wallet_handle, export_config_json, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_import_wallet(indy_handle_t command_handle, char*config, char*credentials, char*import_config_json ) {
	indy_error_t err = indy_import_wallet(command_handle, config, credentials, import_config_json, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_close_wallet(indy_handle_t command_handle, indy_handle_t wallet_handle ) {
	indy_error_t err = indy_close_wallet(command_handle, wallet_handle, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_delete_wallet(indy_handle_t command_handle, char*config, char*credentials ) {
	indy_error_t err = indy_delete_wallet(command_handle, config, credentials, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_generate_wallet_key(indy_handle_t command_handle, char *config ) {
	indy_error_t err = indy_generate_wallet_key(command_handle, config, (indy_handler_str)strHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

