//
// Autogenerated from indy-sdk main header files (indy_*.h)
//

#include <stdio.h>
#include "findy_glue.h"
#include "findy_callback_types.h"

// cgo generated
#include "_cgo_export.h"


#define CALLBACK_FUNCTION_HERE ((indy_handler_str)strHandler)


indy_error_t findy_create_and_store_my_did(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did_json ) {
	indy_error_t err = indy_create_and_store_my_did(command_handle, wallet_handle, did_json, (indy_handler_str_str)strStrHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_replace_keys_start(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did, char *identity_json ) {
	indy_error_t err = indy_replace_keys_start(command_handle, wallet_handle, did, identity_json, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_replace_keys_apply(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did ) {
	indy_error_t err = indy_replace_keys_apply(command_handle, wallet_handle, did, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_store_their_did(indy_handle_t command_handle, indy_handle_t wallet_handle, char *identity_json ) {
	indy_error_t err = indy_store_their_did(command_handle, wallet_handle, identity_json, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_key_for_did(indy_handle_t command_handle, indy_handle_t pool_handle, indy_handle_t wallet_handle, char *did ) {
	indy_error_t err = indy_key_for_did(command_handle, pool_handle, wallet_handle, did, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_key_for_local_did(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did ) {
	indy_error_t err = indy_key_for_local_did(command_handle, wallet_handle, did, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_set_endpoint_for_did(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did, char *address, char *transport_key ) {
	indy_error_t err = indy_set_endpoint_for_did(command_handle, wallet_handle, did, address, transport_key, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_get_endpoint_for_did(indy_handle_t command_handle, indy_handle_t wallet_handle, indy_handle_t pool_handle, char *did ) {
	indy_error_t err = indy_get_endpoint_for_did(command_handle, wallet_handle, pool_handle, did, (indy_handler_str_str)strStrHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_set_did_metadata(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did, char *metadata ) {
	indy_error_t err = indy_set_did_metadata(command_handle, wallet_handle, did, metadata, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_get_did_metadata(indy_handle_t command_handle, indy_handle_t wallet_handle, char *did ) {
	indy_error_t err = indy_get_did_metadata(command_handle, wallet_handle, did, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_get_my_did_with_meta(indy_handle_t command_handle, indy_handle_t wallet_handle, char *my_did ) {
	indy_error_t err = indy_get_my_did_with_meta(command_handle, wallet_handle, my_did, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_list_my_dids_with_meta(indy_handle_t command_handle, indy_handle_t wallet_handle ) {
	indy_error_t err = indy_list_my_dids_with_meta(command_handle, wallet_handle, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_abbreviate_verkey(indy_handle_t command_handle, char *did, char *full_verkey ) {
	indy_error_t err = indy_abbreviate_verkey(command_handle, did, full_verkey, CALLBACK_FUNCTION_HERE );
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

