extern indy_error_t findy_sign_and_submit_request(indy_handle_t command_handle, indy_handle_t pool_handle, indy_handle_t wallet_handle, char *submitter_did, char *request_json);
extern indy_error_t findy_submit_request(indy_handle_t command_handle, indy_handle_t pool_handle, char *request_json);
extern indy_error_t findy_submit_action(indy_handle_t command_handle, indy_handle_t pool_handle, char *request_json, char *nodes, indy_i32_t timeout);
extern indy_error_t findy_sign_request(indy_handle_t command_handle, indy_handle_t wallet_handle, char *submitter_did, char *request_json);
extern indy_error_t findy_multi_sign_request(indy_handle_t command_handle, indy_handle_t wallet_handle, char *submitter_did, char *request_json);
extern indy_error_t findy_build_get_ddo_request(indy_handle_t command_handle, char *submitter_did, char *target_did);
extern indy_error_t findy_build_nym_request(indy_handle_t command_handle, char *submitter_did, char *target_did, char *verkey, char *alias, char *role);
extern indy_error_t findy_build_attrib_request(indy_handle_t command_handle, char *submitter_did, char *target_did, char *hash, char *raw, char *enc);
extern indy_error_t findy_build_get_attrib_request(indy_handle_t command_handle, char *submitter_did, char *target_did, char *hash, char *raw, char *enc);
extern indy_error_t findy_build_get_nym_request(indy_handle_t command_handle, char *submitter_did, char *target_did);
extern indy_error_t findy_build_schema_request(indy_handle_t command_handle, char *submitter_did, char *data);
extern indy_error_t findy_build_get_schema_request(indy_handle_t command_handle, char *submitter_did, char *id);
extern indy_error_t findy_parse_get_schema_response(indy_handle_t command_handle, char *get_schema_response);
extern indy_error_t findy_build_cred_def_request(indy_handle_t command_handle, char *submitter_did, char *data);
extern indy_error_t findy_build_get_cred_def_request(indy_handle_t command_handle, char *submitter_did, char *id);
extern indy_error_t findy_parse_get_cred_def_response(indy_handle_t command_handle, char *get_cred_def_response);
extern indy_error_t findy_build_node_request(indy_handle_t command_handle, char *submitter_did, char *target_did, char *data);
extern indy_error_t findy_build_get_validator_info_request(indy_handle_t command_handle, char *submitter_did);
extern indy_error_t findy_build_get_txn_request(indy_handle_t command_handle, char *submitter_did, char *ledger_type, indy_i32_t seq_no);
extern indy_error_t findy_build_pool_config_request(indy_handle_t command_handle, char *submitter_did, indy_bool_t writes, indy_bool_t force);
extern indy_error_t findy_build_pool_restart_request(indy_handle_t command_handle, char *submitter_did, char *action, char *datetime);
extern indy_error_t findy_build_pool_upgrade_request(indy_handle_t command_handle, char *submitter_did, char *name, char *version, char *action, char *sha256, indy_i32_t timeout, char *schedule, char *justification, indy_bool_t reinstall, indy_bool_t force, char *package_);
extern indy_error_t findy_build_revoc_reg_def_request(indy_handle_t command_handle, char *submitter_did, char *data);
extern indy_error_t findy_build_get_revoc_reg_def_request(indy_handle_t command_handle, char *submitter_did, char *id);
extern indy_error_t findy_parse_get_revoc_reg_def_response(indy_handle_t command_handle, char *get_revoc_ref_def_response);
extern indy_error_t findy_build_revoc_reg_entry_request(indy_handle_t command_handle, char *submitter_did, char *revoc_reg_def_id, char *rev_def_type, char *value);
extern indy_error_t findy_build_get_revoc_reg_request(indy_handle_t command_handle, char *submitter_did, char *revoc_reg_def_id, long long timestamp);
extern indy_error_t findy_parse_get_revoc_reg_response(indy_handle_t command_handle, char *get_revoc_reg_response);
extern indy_error_t findy_build_get_revoc_reg_delta_request(indy_handle_t command_handle, char *submitter_did, char *revoc_reg_def_id, long long from, long long to);
extern indy_error_t findy_parse_get_revoc_reg_delta_response(indy_handle_t command_handle, char *get_revoc_reg_delta_response);
extern indy_error_t findy_get_response_metadata(indy_handle_t command_handle, char *response);
