//
// Autogenerated from indy-sdk main header files (indy_*.h)
//

#include <stdio.h>
#include "findy_glue.h"
#include "findy_callback_types.h"

// cgo generated
#include "_cgo_export.h"

indy_error_t findy_create_key(indy_handle_t command_handle, indy_handle_t wallet_handle, char *key_json ) {
	indy_error_t err = indy_create_key(command_handle, wallet_handle, key_json, (indy_handler_str)strHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_set_key_metadata(indy_handle_t command_handle, indy_handle_t wallet_handle, char *verkey, char *metadata ) {
	indy_error_t err = indy_set_key_metadata(command_handle, wallet_handle, verkey, metadata, (indy_handler)handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_get_key_metadata(indy_handle_t command_handle, indy_handle_t wallet_handle, char *verkey ) {
	indy_error_t err = indy_get_key_metadata(command_handle, wallet_handle, verkey, (indy_handler_str)strHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_crypto_sign(indy_handle_t command_handle, indy_handle_t wallet_handle, char *signer_vk, indy_u8_t *message_raw, indy_u32_t message_len ) {
	indy_error_t err = indy_crypto_sign(command_handle, wallet_handle, signer_vk, message_raw, message_len, (indy_handler_u8ptr_u32)u8ptrU32Handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_crypto_verify(indy_handle_t command_handle, char *signer_vk, indy_u8_t *message_raw, indy_u32_t message_len, indy_u8_t *signature_raw, indy_u32_t signature_len ) {
	indy_error_t err = indy_crypto_verify(command_handle, signer_vk, message_raw, message_len, signature_raw, signature_len, (indy_handler_bool)boolHandler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_crypto_auth_crypt(indy_handle_t command_handle, indy_handle_t wallet_handle, char *sender_vk, char *recipient_vk, indy_u8_t *message_raw, indy_u32_t message_len ) {
	indy_error_t err = indy_crypto_auth_crypt(command_handle, wallet_handle, sender_vk, recipient_vk, message_raw, message_len, (indy_handler_u8ptr_u32)u8ptrU32Handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_crypto_auth_decrypt(indy_handle_t command_handle, indy_handle_t wallet_handle, char *recipient_vk, indy_u8_t *encrypted_msg_raw, indy_u32_t encrypted_msg_len ) {
	indy_error_t err = indy_crypto_auth_decrypt(command_handle, wallet_handle, recipient_vk, encrypted_msg_raw, encrypted_msg_len, (indy_handler_str_u8ptr_u32)strU8ptrU32Handler); //DDD
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_crypto_anon_crypt(indy_handle_t command_handle, char *recipient_vk, indy_u8_t *message_raw, indy_u32_t message_len ) {
	indy_error_t err = indy_crypto_anon_crypt(command_handle, recipient_vk, message_raw, message_len, (indy_handler_u8ptr_u32)u8ptrU32Handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_crypto_anon_decrypt(indy_handle_t command_handle, indy_handle_t wallet_handle, char *recipient_vk, indy_u8_t *encrypted_msg, indy_u32_t encrypted_len ) {
	indy_error_t err = indy_crypto_anon_decrypt(command_handle, wallet_handle, recipient_vk, encrypted_msg, encrypted_len, (indy_handler_u8ptr_u32)u8ptrU32Handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_pack_message(indy_handle_t command_handle, indy_handle_t wallet_handle, indy_u8_t *message, indy_u32_t message_len, char *receiver_keys, char *sender ) {
	indy_error_t err = indy_pack_message(command_handle, wallet_handle, message, message_len, receiver_keys, sender, (indy_handler_u8ptr_u32)u8ptrU32Handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}

indy_error_t findy_unpack_message(indy_handle_t command_handle, indy_handle_t wallet_handle, indy_u8_t *jwe_msg, indy_u32_t jwe_len ) {
	indy_error_t err = indy_unpack_message(command_handle, wallet_handle, jwe_msg, jwe_len, (indy_handler_u8ptr_u32)u8ptrU32Handler);
	if (err != Success) {
		handler(command_handle, err);
	}
	return err;
}